# Generated by Django 2.0.1 on 2018-01-23 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='room_name',
            field=models.CharField(default='display', max_length=255),
        ),
    ]
