# Generated by Django 2.0.1 on 2018-01-29 16:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_event_room_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='event_type',
        ),
    ]
