# Generated by Django 2.0.1 on 2018-01-29 17:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_remove_event_event_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='status',
        ),
    ]
